# Generated by Django 5.0.6 on 2024-06-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='hotelcategory',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotelcategory',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hotelcategory',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
