# Generated by Django 5.0.6 on 2024-06-21 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0003_alter_hotel_hotel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_integration.city'),
        ),
        migrations.AlterField(
            model_name='hotelcategory',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hotelcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hotelcategory',
            name='type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
